from User import *

from PyQt5 import QtCore, QtGui, QtWidgets

class sign_window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 389)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 20, 281, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.First_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.First_lineEdit.setObjectName("First_lineEdit")
        self.verticalLayout_2.addWidget(self.First_lineEdit)
        self.Last_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.Last_lineEdit.setObjectName("Last_lineEdit")
        self.verticalLayout_2.addWidget(self.Last_lineEdit)
        self.User_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.User_lineEdit.setObjectName("User_lineEdit")
        self.verticalLayout_2.addWidget(self.User_lineEdit)
        self.Password_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.Password_lineEdit.setObjectName("Password_lineEdit")
        self.verticalLayout_2.addWidget(self.Password_lineEdit)
        self.Email_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.Email_lineEdit.setObjectName("Email_lineEdit")
        self.verticalLayout_2.addWidget(self.Email_lineEdit)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(90, 20, 81, 171))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(220, 210, 160, 30))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.signup_button = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.signup_button.setObjectName("signup_button")
        self.verticalLayout_4.addWidget(self.signup_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.signup_button.clicked.connect(self.SignButton)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def SignButton(self):
        temp1 = self.First_lineEdit.text()
        temp2 = self.Last_lineEdit.text()
        temp3 = self.User_lineEdit.text()
        temp4 = self.Password_lineEdit.text()
        temp5 = self.Email_lineEdit.text()

        eric = Member(temp1,temp2,temp3,temp4,temp5)
        Customer.addMember(eric)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "First Name"))
        self.label_4.setText(_translate("MainWindow", "Last Name"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.label_3.setText(_translate("MainWindow", "Email"))
        self.signup_button.setText(_translate("MainWindow", "Sign up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = sign_window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
