# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowSalesperson.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Sales_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 697)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.stackedWidget.setObjectName("stackedWidget")
        self.profile = QtWidgets.QWidget()
        self.profile.setObjectName("profile")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.profile)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 100, 181, 491))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_37 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_2.addWidget(self.label_37)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.salesperson_profile = QtWidgets.QLabel(self.profile)
        self.salesperson_profile.setGeometry(QtCore.QRect(40, 40, 121, 16))
        self.salesperson_profile.setObjectName("salesperson_profile")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.profile)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(220, 100, 201, 491))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.name = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.name.setObjectName("name")
        self.verticalLayout_4.addWidget(self.name)
        self.restaurant = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.restaurant.setObjectName("restaurant")
        self.verticalLayout_4.addWidget(self.restaurant)
        self.budget = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.budget.setObjectName("budget")
        self.verticalLayout_4.addWidget(self.budget)
        self.rating = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.rating.setObjectName("rating")
        self.verticalLayout_4.addWidget(self.rating)
        self.deal_of_the_day = QtWidgets.QLabel(self.profile)
        self.deal_of_the_day.setGeometry(QtCore.QRect(540, 100, 131, 16))
        self.deal_of_the_day.setObjectName("deal_of_the_day")
        self.pushButton_39 = QtWidgets.QPushButton(self.profile)
        self.pushButton_39.setGeometry(QtCore.QRect(230, 30, 113, 32))
        self.pushButton_39.setObjectName("pushButton_39")
        self.stackedWidget.addWidget(self.profile)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(300, 30, 171, 16))
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(60, 80, 661, 80))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.listWidget = QtWidgets.QListWidget(self.page)
        self.listWidget.setGeometry(QtCore.QRect(60, 160, 321, 471))
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.listWidget_2 = QtWidgets.QListWidget(self.page)
        self.listWidget_2.setGeometry(QtCore.QRect(390, 160, 331, 471))
        self.listWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.pushButton_40 = QtWidgets.QPushButton(self.page)
        self.pushButton_40.setGeometry(QtCore.QRect(20, 10, 113, 32))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(self.page)
        self.pushButton_41.setGeometry(QtCore.QRect(590, 10, 131, 32))
        self.pushButton_41.setObjectName("pushButton_41")
        self.stackedWidget.addWidget(self.page)
        self.select_supplier = QtWidgets.QWidget()
        self.select_supplier.setObjectName("select_supplier")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.select_supplier)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 110, 221, 371))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.supplier_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.supplier_1.setObjectName("supplier_1")
        self.horizontalLayout_2.addWidget(self.supplier_1)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.select_supplier)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(270, 110, 211, 371))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.supplier_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.supplier_4.setObjectName("supplier_4")
        self.horizontalLayout_3.addWidget(self.supplier_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.select_supplier)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(510, 110, 221, 371))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.supplier_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.supplier_5.setObjectName("supplier_5")
        self.horizontalLayout_4.addWidget(self.supplier_5)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.label = QtWidgets.QLabel(self.select_supplier)
        self.label.setGeometry(QtCore.QRect(350, 50, 60, 16))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.select_supplier)
        self.suppler_1 = QtWidgets.QWidget()
        self.suppler_1.setObjectName("suppler_1")
        self.label_6 = QtWidgets.QLabel(self.suppler_1)
        self.label_6.setGeometry(QtCore.QRect(330, 20, 60, 16))
        self.label_6.setObjectName("label_6")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.suppler_1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 761, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.item_list_1 = QtWidgets.QListWidget(self.suppler_1)
        self.item_list_1.setGeometry(QtCore.QRect(0, 80, 191, 541))
        self.item_list_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.item_list_1.setObjectName("item_list_1")
        item = QtWidgets.QListWidgetItem()
        self.item_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_1.addItem(item)
        self.quality_list_1 = QtWidgets.QListWidget(self.suppler_1)
        self.quality_list_1.setGeometry(QtCore.QRect(190, 80, 181, 541))
        self.quality_list_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.quality_list_1.setObjectName("quality_list_1")
        item = QtWidgets.QListWidgetItem()
        self.quality_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_1.addItem(item)
        self.price_list_1 = QtWidgets.QListWidget(self.suppler_1)
        self.price_list_1.setGeometry(QtCore.QRect(370, 80, 171, 541))
        self.price_list_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.price_list_1.setObjectName("price_list_1")
        item = QtWidgets.QListWidgetItem()
        self.price_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_1.addItem(item)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.suppler_1)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(550, 80, 160, 391))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_10 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_13 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_3.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_3.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_3.addWidget(self.pushButton_15)
        self.pushButton_12 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_3.addWidget(self.pushButton_12)
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_38 = QtWidgets.QPushButton(self.suppler_1)
        self.pushButton_38.setGeometry(QtCore.QRect(0, 10, 113, 32))
        self.pushButton_38.setObjectName("pushButton_38")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.suppler_1)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(540, 20, 201, 21))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_9.addWidget(self.label_31)
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_9.addWidget(self.label_30)
        self.stackedWidget.addWidget(self.suppler_1)
        self.supplier_2 = QtWidgets.QWidget()
        self.supplier_2.setObjectName("supplier_2")
        self.label_2 = QtWidgets.QLabel(self.supplier_2)
        self.label_2.setGeometry(QtCore.QRect(350, 30, 60, 16))
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.supplier_2)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 60, 751, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_5.addWidget(self.label_25)
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_5.addWidget(self.label_24)
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_5.addWidget(self.label_23)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_5.addWidget(self.label_22)
        self.item_list_2 = QtWidgets.QListWidget(self.supplier_2)
        self.item_list_2.setGeometry(QtCore.QRect(10, 90, 181, 541))
        self.item_list_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.item_list_2.setObjectName("item_list_2")
        item = QtWidgets.QListWidgetItem()
        self.item_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_2.addItem(item)
        self.quality_list_2 = QtWidgets.QListWidget(self.supplier_2)
        self.quality_list_2.setGeometry(QtCore.QRect(190, 90, 191, 541))
        self.quality_list_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.quality_list_2.setObjectName("quality_list_2")
        item = QtWidgets.QListWidgetItem()
        self.quality_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_2.addItem(item)
        self.price_list_2 = QtWidgets.QListWidget(self.supplier_2)
        self.price_list_2.setGeometry(QtCore.QRect(380, 90, 191, 541))
        self.price_list_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.price_list_2.setObjectName("price_list_2")
        item = QtWidgets.QListWidgetItem()
        self.price_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_2.addItem(item)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.supplier_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(580, 100, 161, 381))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_19 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_5.addWidget(self.pushButton_19)
        self.pushButton_21 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_5.addWidget(self.pushButton_21)
        self.pushButton_22 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_5.addWidget(self.pushButton_22)
        self.pushButton_24 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_5.addWidget(self.pushButton_24)
        self.pushButton_17 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_5.addWidget(self.pushButton_17)
        self.pushButton_25 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_5.addWidget(self.pushButton_25)
        self.pushButton_23 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_5.addWidget(self.pushButton_23)
        self.pushButton_18 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_5.addWidget(self.pushButton_18)
        self.pushButton_20 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_5.addWidget(self.pushButton_20)
        self.pushButton_16 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_5.addWidget(self.pushButton_16)
        self.pushButton_37 = QtWidgets.QPushButton(self.supplier_2)
        self.pushButton_37.setGeometry(QtCore.QRect(10, 20, 113, 32))
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.supplier_2)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(550, 20, 185, 31))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_33 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_8.addWidget(self.label_33)
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_8.addWidget(self.label_32)
        self.stackedWidget.addWidget(self.supplier_2)
        self.supplier_3 = QtWidgets.QWidget()
        self.supplier_3.setObjectName("supplier_3")
        self.label_7 = QtWidgets.QLabel(self.supplier_3)
        self.label_7.setGeometry(QtCore.QRect(350, 30, 71, 16))
        self.label_7.setObjectName("label_7")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.supplier_3)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 50, 761, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_6.addWidget(self.label_29)
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_6.addWidget(self.label_28)
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_6.addWidget(self.label_27)
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_6.addWidget(self.label_26)
        self.item_list_3 = QtWidgets.QListWidget(self.supplier_3)
        self.item_list_3.setGeometry(QtCore.QRect(10, 90, 181, 541))
        self.item_list_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.item_list_3.setObjectName("item_list_3")
        item = QtWidgets.QListWidgetItem()
        self.item_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.item_list_3.addItem(item)
        self.quality_list_3 = QtWidgets.QListWidget(self.supplier_3)
        self.quality_list_3.setGeometry(QtCore.QRect(190, 90, 191, 541))
        self.quality_list_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.quality_list_3.setObjectName("quality_list_3")
        item = QtWidgets.QListWidgetItem()
        self.quality_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.quality_list_3.addItem(item)
        self.price_list_3 = QtWidgets.QListWidget(self.supplier_3)
        self.price_list_3.setGeometry(QtCore.QRect(380, 90, 181, 541))
        self.price_list_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.price_list_3.setObjectName("price_list_3")
        item = QtWidgets.QListWidgetItem()
        self.price_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.price_list_3.addItem(item)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.supplier_3)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(570, 90, 160, 401))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_27 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_6.addWidget(self.pushButton_27)
        self.pushButton_30 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_6.addWidget(self.pushButton_30)
        self.pushButton_31 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_31.setObjectName("pushButton_31")
        self.verticalLayout_6.addWidget(self.pushButton_31)
        self.pushButton_34 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_34.setObjectName("pushButton_34")
        self.verticalLayout_6.addWidget(self.pushButton_34)
        self.pushButton_33 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_33.setObjectName("pushButton_33")
        self.verticalLayout_6.addWidget(self.pushButton_33)
        self.pushButton_35 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_35.setObjectName("pushButton_35")
        self.verticalLayout_6.addWidget(self.pushButton_35)
        self.pushButton_32 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_32.setObjectName("pushButton_32")
        self.verticalLayout_6.addWidget(self.pushButton_32)
        self.pushButton_29 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout_6.addWidget(self.pushButton_29)
        self.pushButton_28 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_6.addWidget(self.pushButton_28)
        self.pushButton_26 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_6.addWidget(self.pushButton_26)
        self.pushButton_36 = QtWidgets.QPushButton(self.supplier_3)
        self.pushButton_36.setGeometry(QtCore.QRect(10, 10, 113, 32))
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.supplier_3)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(534, 10, 201, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_35 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_7.addWidget(self.label_35)
        self.label_34 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_7.addWidget(self.label_34)
        self.stackedWidget.addWidget(self.supplier_3)
        self.check_out = QtWidgets.QWidget()
        self.check_out.setObjectName("check_out")
        self.label_8 = QtWidgets.QLabel(self.check_out)
        self.label_8.setGeometry(QtCore.QRect(340, 40, 71, 16))
        self.label_8.setObjectName("label_8")
        self.check_out_list = QtWidgets.QListWidget(self.check_out)
        self.check_out_list.setGeometry(QtCore.QRect(250, 60, 261, 511))
        self.check_out_list.setObjectName("check_out_list")
        self.label_10 = QtWidgets.QLabel(self.check_out)
        self.label_10.setGeometry(QtCore.QRect(250, 590, 60, 16))
        self.label_10.setObjectName("label_10")
        self.total_amount = QtWidgets.QLabel(self.check_out)
        self.total_amount.setGeometry(QtCore.QRect(290, 590, 60, 16))
        self.total_amount.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.total_amount.setObjectName("total_amount")
        self.pushButton_4 = QtWidgets.QPushButton(self.check_out)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 20, 113, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.check_out)
        self.pushButton_5.setGeometry(QtCore.QRect(400, 580, 113, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.check_out)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_37.setText(_translate("MainWindow", "Name:"))
        self.label_16.setText(_translate("MainWindow", "Restuarant:"))
        self.label_18.setText(_translate("MainWindow", "Budget of the Day:"))
        self.label_20.setText(_translate("MainWindow", "Rating:"))
        self.salesperson_profile.setText(_translate("MainWindow", "Salesperson Profile"))
        self.name.setText(_translate("MainWindow", "name example"))
        self.restaurant.setText(_translate("MainWindow", "Restuarant example"))
        self.budget.setText(_translate("MainWindow", "$1000.00"))
        self.rating.setText(_translate("MainWindow", "1 "))
        self.deal_of_the_day.setText(_translate("MainWindow", "DEALS OF THE DAY"))
        self.pushButton_39.setText(_translate("MainWindow", "Settings"))
        self.label_3.setText(_translate("MainWindow", "Inventory Required by Cook"))
        self.label_5.setText(_translate("MainWindow", "Amount by lb"))
        self.label_4.setText(_translate("MainWindow", "Item"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget_2.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget_2.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget_2.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget_2.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget_2.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget_2.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget_2.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton_40.setText(_translate("MainWindow", "Return"))
        self.pushButton_41.setText(_translate("MainWindow", "Choose Suppliers"))
        self.supplier_1.setText(_translate("MainWindow", "Supplier 1"))
        self.pushButton.setText(_translate("MainWindow", "Shop Here"))
        self.supplier_4.setText(_translate("MainWindow", "Supplier 2"))
        self.pushButton_2.setText(_translate("MainWindow", "Shop Here"))
        self.supplier_5.setText(_translate("MainWindow", "Supplier 3"))
        self.pushButton_3.setText(_translate("MainWindow", "Shop Here"))
        self.label.setText(_translate("MainWindow", "Suppliers"))
        self.label_6.setText(_translate("MainWindow", "Supplier 1"))
        self.label_15.setText(_translate("MainWindow", "Add"))
        self.label_14.setText(_translate("MainWindow", "Price per lb"))
        self.label_13.setText(_translate("MainWindow", "Quality"))
        self.label_12.setText(_translate("MainWindow", "Item"))
        __sortingEnabled = self.item_list_1.isSortingEnabled()
        self.item_list_1.setSortingEnabled(False)
        item = self.item_list_1.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_1.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_1.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_1.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_1.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_1.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_1.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_1.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_1.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_1.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        self.item_list_1.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.quality_list_1.isSortingEnabled()
        self.quality_list_1.setSortingEnabled(False)
        item = self.quality_list_1.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_1.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_1.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_1.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_1.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_1.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_1.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_1.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_1.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_1.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        self.quality_list_1.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.price_list_1.isSortingEnabled()
        self.price_list_1.setSortingEnabled(False)
        item = self.price_list_1.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_1.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_1.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_1.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_1.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_1.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_1.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_1.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_1.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_1.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        self.price_list_1.setSortingEnabled(__sortingEnabled)
        self.pushButton_7.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_8.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_10.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_11.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_13.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_14.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_15.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_12.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_9.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_6.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_38.setText(_translate("MainWindow", "Return"))
        self.label_31.setText(_translate("MainWindow", "$1000.00"))
        self.label_30.setText(_translate("MainWindow", "Budget Remaining:"))
        self.label_2.setText(_translate("MainWindow", "Supplier 2"))
        self.label_25.setText(_translate("MainWindow", "Add"))
        self.label_24.setText(_translate("MainWindow", "Price per lb"))
        self.label_23.setText(_translate("MainWindow", "Quality"))
        self.label_22.setText(_translate("MainWindow", "Item"))
        __sortingEnabled = self.item_list_2.isSortingEnabled()
        self.item_list_2.setSortingEnabled(False)
        item = self.item_list_2.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_2.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_2.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_2.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_2.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_2.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_2.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_2.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_2.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_2.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        self.item_list_2.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.quality_list_2.isSortingEnabled()
        self.quality_list_2.setSortingEnabled(False)
        item = self.quality_list_2.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_2.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_2.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_2.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_2.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_2.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_2.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_2.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_2.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_2.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        self.quality_list_2.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.price_list_2.isSortingEnabled()
        self.price_list_2.setSortingEnabled(False)
        item = self.price_list_2.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_2.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_2.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_2.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_2.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_2.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_2.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_2.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_2.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_2.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        self.price_list_2.setSortingEnabled(__sortingEnabled)
        self.pushButton_19.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_21.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_22.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_24.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_17.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_25.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_23.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_18.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_20.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_16.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_37.setText(_translate("MainWindow", "Return"))
        self.label_33.setText(_translate("MainWindow", "$1000.00"))
        self.label_32.setText(_translate("MainWindow", "Budget Remaining:"))
        self.label_7.setText(_translate("MainWindow", "Supplier 3"))
        self.label_29.setText(_translate("MainWindow", "Add"))
        self.label_28.setText(_translate("MainWindow", "Price per lb"))
        self.label_27.setText(_translate("MainWindow", "Quality"))
        self.label_26.setText(_translate("MainWindow", "Item"))
        __sortingEnabled = self.item_list_3.isSortingEnabled()
        self.item_list_3.setSortingEnabled(False)
        item = self.item_list_3.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_3.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_3.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_3.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_3.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_3.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_3.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_3.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_3.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.item_list_3.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        self.item_list_3.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.quality_list_3.isSortingEnabled()
        self.quality_list_3.setSortingEnabled(False)
        item = self.quality_list_3.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_3.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_3.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_3.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_3.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_3.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_3.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_3.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_3.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.quality_list_3.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        self.quality_list_3.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.price_list_3.isSortingEnabled()
        self.price_list_3.setSortingEnabled(False)
        item = self.price_list_3.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_3.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_3.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_3.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_3.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_3.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_3.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_3.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_3.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.price_list_3.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        self.price_list_3.setSortingEnabled(__sortingEnabled)
        self.pushButton_27.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_30.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_31.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_34.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_33.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_35.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_32.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_29.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_28.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_26.setText(_translate("MainWindow", "Add to Cart"))
        self.pushButton_36.setText(_translate("MainWindow", "Return"))
        self.label_35.setText(_translate("MainWindow", "$1000.00"))
        self.label_34.setText(_translate("MainWindow", "Budget Remaining:"))
        self.label_8.setText(_translate("MainWindow", "Check Out"))
        self.label_10.setText(_translate("MainWindow", "Total:"))
        self.total_amount.setText(_translate("MainWindow", "$0.00"))
        self.pushButton_4.setText(_translate("MainWindow", "Return"))
        self.pushButton_5.setText(_translate("MainWindow", "Confirm Order"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Sales_Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

