# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chefmenuPreview.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Name_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.Name_listWidget.setEnabled(True)
        self.Name_listWidget.setGeometry(QtCore.QRect(140, 50, 401, 561))
        self.Name_listWidget.setAutoFillBackground(False)
        self.Name_listWidget.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.Name_listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Name_listWidget.setLineWidth(0)
        self.Name_listWidget.setObjectName("Name_listWidget")
        item = QtWidgets.QListWidgetItem()
        self.Name_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Name_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Name_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Name_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Name_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Name_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Name_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Name_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Name_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.Name_listWidget.addItem(item)
        self.Price_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.Price_listWidget.setGeometry(QtCore.QRect(550, 50, 91, 561))
        self.Price_listWidget.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.Price_listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Price_listWidget.setObjectName("Price_listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Price_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Price_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Price_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Price_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Price_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Price_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Price_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Price_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Price_listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Price_listWidget.addItem(item)
        self.gobackButton = QtWidgets.QPushButton(self.centralwidget)
        self.gobackButton.setGeometry(QtCore.QRect(0, 0, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gobackButton.setFont(font)
        self.gobackButton.setObjectName("gobackButton")
        self.menupreviewLabel = QtWidgets.QLabel(self.centralwidget)
        self.menupreviewLabel.setGeometry(QtCore.QRect(180, 0, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.menupreviewLabel.setFont(font)
        self.menupreviewLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.menupreviewLabel.setObjectName("menupreviewLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.Name_listWidget.isSortingEnabled()
        self.Name_listWidget.setSortingEnabled(False)
        item = self.Name_listWidget.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.Name_listWidget.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.Name_listWidget.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.Name_listWidget.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.Name_listWidget.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.Name_listWidget.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.Name_listWidget.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.Name_listWidget.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.Name_listWidget.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.Name_listWidget.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        self.Name_listWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.Price_listWidget.isSortingEnabled()
        self.Price_listWidget.setSortingEnabled(False)
        item = self.Price_listWidget.item(0)
        item.setText(_translate("MainWindow", "10"))
        item = self.Price_listWidget.item(1)
        item.setText(_translate("MainWindow", "10"))
        item = self.Price_listWidget.item(2)
        item.setText(_translate("MainWindow", "10"))
        item = self.Price_listWidget.item(3)
        item.setText(_translate("MainWindow", "10"))
        item = self.Price_listWidget.item(4)
        item.setText(_translate("MainWindow", "10"))
        item = self.Price_listWidget.item(5)
        item.setText(_translate("MainWindow", "10"))
        item = self.Price_listWidget.item(6)
        item.setText(_translate("MainWindow", "10"))
        item = self.Price_listWidget.item(7)
        item.setText(_translate("MainWindow", "10"))
        item = self.Price_listWidget.item(8)
        item.setText(_translate("MainWindow", "10"))
        item = self.Price_listWidget.item(9)
        item.setText(_translate("MainWindow", "10"))
        self.Price_listWidget.setSortingEnabled(__sortingEnabled)
        self.gobackButton.setText(_translate("MainWindow", "Go back"))
        self.menupreviewLabel.setText(_translate("MainWindow", "Menu Preview"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
